#!/bin/bash

REMOTE_IP=$1
USER=pi # make sure you have an ssh key copied to bypass password automation
DIRECTORY_NAME=static-html
DEPLOYMENT_DIRECTORY=/home/pi/generic-web-host/ # make sure the user has access!

cp -r ./dist $DIRECTORY_NAME
scp -r ./$DIRECTORY_NAME pi@$REMOTE_IP://$DEPLOYMENT_DIRECTORY
rm -rf ./$DIRECTORY_NAME
