name: 'deploy via scp'

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Build Angular Project
        run: |
          npm ci
          npm run build:prod

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          path: deployment/dist/
          remote_path: ${{ secrets.REMOTE }}
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.KEY }}
